// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHJsKfJFWq-2G_bJpPaX-6BxNWnTpE6jc',
    appId: '1:958103961977:web:35b57aaf4d673dc2e22fa8',
    messagingSenderId: '958103961977',
    projectId: 'resume-1793e',
    authDomain: 'resume-1793e.firebaseapp.com',
    storageBucket: 'resume-1793e.appspot.com',
    measurementId: 'G-TWQ3W4PLNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZoNIm9dCeRq_ivkSK2Qw79Q7zYAR-pa8',
    appId: '1:958103961977:android:0161bc8a26edde51e22fa8',
    messagingSenderId: '958103961977',
    projectId: 'resume-1793e',
    storageBucket: 'resume-1793e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDdR-CsLQWK_wuSorTsAcVopykm3lL9cc',
    appId: '1:958103961977:ios:3538b163cfb5988ee22fa8',
    messagingSenderId: '958103961977',
    projectId: 'resume-1793e',
    storageBucket: 'resume-1793e.appspot.com',
    iosClientId: '958103961977-cc79s5vbugvogjd25rrmcc21bp7ob3vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.resumemanagement',
  );
}
